---
ID: "ddec6b86-8b71-4b1a-8e7a-8a0f58338f47"
Parent: "65330cc9-8c49-462c-93e4-82ccf03e089d"
Template: "65330cc9-8c49-462c-93e4-82ccf03e089d"
Path: "/sitecore/templates/Project/sitecoredemo-jp/Headless Site/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220915T070236Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shinhara@sitecore.net
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shinhara@sitecore.net
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c9447002-d63c-4d85-8d2e-88d847e56be3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shinhara@sitecore.net
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220915T070236Z
